export const SET_ACTIVITY_TYPE = 'SET_ACTIVITY_TYPE';
export const SET_ACTIVITY_DURATION = 'SET_ACTIVITY_DURATION';
export const SET_ACTIVITY_SLOT = 'SET_ACTIVITY_SLOT';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';

export const FETCH_ACTIVITIES_START = 'FETCH_ACTIVITIES';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_ERROR = 'FETCH_ACTIVITIES_ERROR';